import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import assert from 'node:assert/strict';
import { spawn, execFileSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';
import { seedDemo } from '../../scripts/demo-data.mjs';
const {chromium}=await import(process.env.PLAYWRIGHT_MODULE||'playwright');
const repo=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'../..');
const scratch=fs.mkdtempSync(path.join(os.tmpdir(),'espacio-local-video-')),demo=seedDemo(scratch);
const media=path.join(repo,'docs','media');fs.mkdirSync(media,{recursive:true});
const child=spawn(process.execPath,['server.js'],{cwd:repo,env:{...process.env,HOME:demo.home,USERPROFILE:demo.home,DASHBOARD_DATA_DIR:demo.dataDir,DASHBOARD_PROJECTS_DIR:demo.projectsDir,DASHBOARD_WORK_DIR:path.join(demo.home,'dev','Work'),DASHBOARD_VAULT_DIR:path.join(demo.home,'vault'),CODEX_HOME:path.join(demo.home,'.codex'),GROK_HOME:path.join(demo.home,'.grok'),AGY_HOME:path.join(demo.home,'.gemini','antigravity-cli'),DASHBOARD_ENABLE_AI:'0',DASHBOARD_ENABLE_GIT_WRITE:'0',DASHBOARD_DEMO:'1',PORT:'4958'},stdio:'ignore'});
let browser,context,page;
const errors=[],external=[];
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
try {
 for(let i=0;i<80;i++){try{if((await fetch('http://127.0.0.1:4958/api/stats')).ok)break;}catch{}await sleep(100);}
 browser=await chromium.launch({headless:true,...(process.env.VIDEO_BROWSER_CHANNEL?{channel:process.env.VIDEO_BROWSER_CHANNEL}:{})});
 context=await browser.newContext({viewport:{width:1280,height:900},recordVideo:{dir:scratch,size:{width:1280,height:900}},colorScheme:'light'});
 page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>{if(!r.url().startsWith('http://127.0.0.1:4958'))external.push(r.url())});
 await page.goto('http://127.0.0.1:4958',{waitUntil:'networkidle'});
 await page.waitForSelector('#demoBanner');
 await page.addStyleTag({content:'.demo-banner{margin-bottom:8px} #walkthrough{position:fixed;bottom:0;left:0;right:0;z-index:10000;background:#28241ff2;color:#fff;padding:18px 32px;font:500 20px system-ui;border-top:3px solid #b3643e;pointer-events:none}'});
 const caption=async(message,seconds=5)=>{await page.evaluate(text=>{let el=document.getElementById('walkthrough');if(!el){el=document.createElement('div');el.id='walkthrough';document.body.append(el)}el.textContent=`DEMO · ${text}`},message);await sleep(seconds*1000)};
 await caption('Espacio local · uso de IA, proyectos y tareas en tu equipo',5);
 await caption('Instalar: git clone → cd claude-dashboard → npm start',5);
 await page.locator('.tier-tab[data-tier=agents]').click();
 await page.locator('[data-agent=codex][data-enabled=true]').click();
 await caption('Conecta los registros locales de Codex, Grok y Antigravity CLI',5);
 await page.locator('.tier-tab[data-tier=kanban]').click();
 await sleep(350);await page.evaluate(()=>{window.scrollTo({top:0,behavior:'instant'});document.getElementById('walkthrough').hidden=true;});
 await page.screenshot({path:path.join(media,'kanban.png'),fullPage:true});
 await page.evaluate(()=>document.getElementById('walkthrough').hidden=false);
 await caption('Mi trabajo: filtra tareas por proyecto y responsable IA',5);
 await page.locator('#boardNew').click();
 await page.locator('#taskForm [name=title]').fill('Probar una mejora con teclado');
 await page.locator('#taskForm [name=project]').selectOption('agent-kit');
 await page.locator('#taskForm [name=agent]').selectOption('claude');
 await page.locator('#taskForm [name=acceptance]').fill('Foco visible, navegación completa y pruebas documentadas.');
 await caption('Crea una tarea con objetivo, responsable y criterios de aceptación',5);
 await page.locator('#taskSave').click();
 const card=page.locator('.board-task').filter({hasText:'Probar una mejora con teclado'});
 await card.locator('[data-move]').selectOption('doing');
 await caption('Mueve el trabajo: Por hacer → En curso → En revisión → Listo',5);
 await card.locator('.task-title').click();
 await page.locator('#taskForm [name=handoff]').fill('Entrega de ejemplo: revisión lista; faltan pruebas de integración.');
 await caption('Deja contexto: cambios, pruebas y bloqueos para la siguiente IA',5);
 await page.locator('#taskSave').click();
 await page.locator('.tier-tab[data-tier=radar]').click();await page.locator('[data-collection=credits]').click();
 await caption('Radar: créditos AWS con condiciones y fuentes para revisar',5);
 await page.locator('[data-collection=jobs]').click();
 await caption('Empleo: filtra región y compara tecnologías con tu CV local',5);
 await page.locator('.tier-tab[data-tier=kanban]').click();
 await page.locator('#boardPlanner summary').click();
 await caption('En tu instalación: el planificador Claude propone tareas revisables',5);
 await page.locator('#boardPlanner summary').click();
 await page.setViewportSize({width:390,height:844});
 assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));
 await page.screenshot({path:path.join(media,'mobile.png')});
 await caption('Prueba primero npm run demo · datos sintéticos, sin leer tu historial',5);
 await page.setViewportSize({width:1280,height:900});await page.evaluate(()=>document.documentElement.dataset.theme='dark');
 await caption('Espacio local · github.com/DavidRm1911/claude-dashboard',5);
 assert.deepEqual(errors,[]);assert.deepEqual(external,[]);
 const raw=await page.video().path();await context.close();context=null;
 execFileSync('ffmpeg',['-hide_banner','-loglevel','error','-y','-i',raw,'-vf','scale=1280:900:flags=lanczos','-c:v','libx264','-preset','veryfast','-crf','25','-pix_fmt','yuv420p','-movflags','+faststart','-an',path.join(media,'uso.mp4')],{timeout:180000});
 execFileSync('ffmpeg',['-hide_banner','-loglevel','error','-y','-ss','16','-t','5','-i',raw,'-vf','fps=8,scale=720:-1:flags=lanczos,split[a][b];[a]palettegen[p];[b][p]paletteuse','-loop','0',path.join(media,'preview.gif')],{timeout:120000});
 console.log('Video y capturas listos. Demo aislada, cero errores JS, cero solicitudes externas.');
}finally{await context?.close();await browser?.close();child.kill('SIGTERM');fs.rmSync(scratch,{recursive:true,force:true});}
